### ISSUE TITLE
Entangled Crashing game when used

### ISSUE THREAD

**Issue by DinnerBeef** [SuperMartijn642/Entangled1.12#1]
https://pastebin.com/qHUMGUKw

Using this on a mekisnam infuser

**Comment by DinnerBeef** [comment]
bit more info on this it only crashes when I look at it.

**Comment by SuperMartijn642** [comment]
Ah I forgot mods like The One Probe and Waila request capabilities client side

**Comment by SuperMartijn642** [comment]
Should be fixed now, thanks for the report

**Comment by DinnerBeef** [comment]
thanks, I can not use for what I wanted to an make things look nicer
