### ISSUE TITLE
[Feature] Display binding target

### ISSUE THREAD

**Issue by uecasm** [SuperMartijn642/Entangled1.12#10]
The main idea is that it'd be good to have some way to interact with a programmed Entangled Block to find the coordinates that it was entangled with.  Sometimes you've set multiple blocks to point at different but similar-looking other blocks and it can be hard to remember which is which later on.

Either have another tool, or a query mode on the existing tool, or perhaps just right-clicking the block with an empty hand could show the coordinates in a tooltip or in chat.  Perhaps a OneProbe integration?

Or the idea of having tool modes leads into a separate (and less needed, but probably still useful) idea: a way to "copy" an existing entangled block's target back onto the Binder so that you can bind another block to the same target without needing to go back to that original target yourself.  (Especially useful where that target is in another dimension.)  Since the Binder does display its bound coordinates, this could also be an alternative to the first idea.

**Comment by SuperMartijn642** [comment]
I added support for The One Probe now in version 1.3.5.

I'll look into other options that don't require The One Probe or WAILA in a future update.

**Comment by SuperMartijn642** [comment]
Since you created this, entangled blocks now keep their data when picked up. The tooltip on the item will show what block it is bound to as well as the coordinates of that block.
I feel that that, plus the integration with The One Probe and WAILA/Jade, is sufficient.

Thank you for the suggestion!

**Comment by uecasm** [comment]
Well, that doesn't cover the "copy/paste" case.  One other idea for that, if data is retained now, would be to craft a programmed block together with an unprogrammed block to duplicate the data (i.e. get two programmed blocks).  It's not quite as convenient as a tool since you'd have to break the programmed block to use it as a template.  Though a tool(/mode) is probably easier to code too.
