### ISSUE TITLE
[Feature] Not sure if it's a feature request or a bug tbh

### ISSUE THREAD

**Issue by IamStig** [SuperMartijn642/Entangled1.12#11]
Is your feature request related to a problem? Please describe.
**The problem is simple - the Pneumaticcraft Pressurized Spawner shows as being linked (model shows the spawner block) but the Entangled block does not pass on a redstone signal to turn the spawner on.**

Describe the solution you'd like
**Um....just allowing the redstone pass through would be great.

Love the mod...when it works...thanks**

**Comment by SuperMartijn642** [comment]
I'm going to close this issue as it seems to be similar to newer #13 and that one describes it a bit more broadly.
