### ISSUE TITLE
[1.16.5] can't transfer energy

### ISSUE THREAD

**Issue by EnterFor** [SuperMartijn642/Entangled1.12#12]
**Version Info**
- Minecraft：1.16.5
- Entangled：1.2.10
- Forge：36.0.15

**Description of the Bug**
Use MEK test, unable to transmit energy
Using Powah test, the transmission is also impossible.
Items can be transferred

**Steps to Reproduce**
I am not good at English, can I take a screenshot to show it?

**Screenshots**
![image](https://user-images.githubusercontent.com/10114685/107340180-6abae900-6af8-11eb-8679-789c373ce95e.png)
![image](https://user-images.githubusercontent.com/10114685/107340445-bec5cd80-6af8-11eb-9701-ad802d80d534.png)

**Comment by EnterFor** [comment]
![image](https://user-images.githubusercontent.com/10114685/107343025-e23e4780-6afb-11eb-8bb7-76642c1813fe.png)
By the way, one of the translations did not show

**Comment by SuperMartijn642** [comment]
![image](https://user-images.githubusercontent.com/12382965/108239459-396e9880-714a-11eb-8672-095617b7e9ce.png)
Here's an example:
The red block cannot push to or pull from the blue block.
The blue block can push to and pull from the red block.

Either setting the cable in your example to pull,
![image](https://user-images.githubusercontent.com/12382965/108239851-979b7b80-714a-11eb-94cf-925eb5f48ac9.png)
or switching around the block that's entangled
![image](https://user-images.githubusercontent.com/12382965/108240064-c6195680-714a-11eb-8c95-38356374e4c1.png)
will work.

Sadly there's nothing I can do to make your examples work. A block simply only expects 6 blocks to be touching it and thus only interacts with those blocks.

As for the missing language key, I fixed it now in version 1.2.11.
