### ISSUE TITLE
[Feature] Redstone integration for entangled block

### ISSUE THREAD

**Issue by AbacusOperator** [SuperMartijn642/Entangled1.12#13]
**Is your feature request related to a problem? Please describe.**
In current version of the mod, entangled block doesn't allow actions associated with redstone signal systems such as:

- Transmission of redstone signal both ways through entanglement link.
- Comparator analysis of bound block through the entanglement block.
- Observer analysis of change of state of bound block through the entanglement block.

**Describe the solution you'd like**
- Redstone signal that bound block transmits to each entangled block is equal to whatever signal it would output to its surrounding from corresponding side.
- Bound block receives a signal from all connected entangled blocks that is equal to their sum, unless this sum is greater than 15.
- Comparator adjacent to entangled block outputs a signal it would output if it was adjacent to an actual block.
- Observer adjacent to entangled block outputs pulse signal upon bounded block state change as it would if it was adjacent to it.

**Comment by Naddox** [comment]
Came here to request this feature also. Trying to use a comparator on the entangle block, this would be extremely useful for making redstone setups extremely clean.

**Comment by trogarus** [comment]
Can I second this request? Would be particularly useful for mekanism machines, and others, that would allow redstone signal to turn them on and off.

**Comment by SuperMartijn642** [comment]
I now added the following
> - Redstone signal that bound block transmits to each entangled block is equal to whatever signal it would output to its surrounding from corresponding side.
> - Comparator adjacent to entangled block outputs a signal it would output if it was adjacent to an actual block.
Sadly, the other two, observers and redstone the other way, are not possible within Minecrafts limitations.

It is available now in Entangled 1.3.7.

Thank you for the suggestions!
