### ISSUE TITLE
[Crash] java.lang.NullPointerException: Rendering Block Entity

### ISSUE THREAD

**Issue by dj-holy** [SuperMartijn642/Entangled1.12#14]
**Version Info**
- Minecraft, 1.16.5
- Entangled, 	entangled-1.2.11-mc1.16.5

**Steps to Reproduce**
Bind Entagnled Block to an Industrial Foregoing Black Hole Tank Crashes Client but not Server.

**Crash report (~/logs/latest.log)**
...
[crash-2021-03-14_10.36.51-client.txt](https://github.com/SuperMartijn642/Entangled1.12/files/6136394/crash-2021-03-14_10.36.51-client.txt)

**Comment by SuperMartijn642** [comment]
It seems to be an issue with Industrial Foregoing. I made [a pull request to fix it](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/pull/1057).

Otherwise I will add the Black Hole Tank to a blacklist for block rendering.

**Comment by SuperMartijn642** [comment]
The pull request has been merged, so it should be fixed in the next release of industrial foregoing.

Thank you for reporting the issue!
