### ISSUE TITLE
[Bug] Link to the Mekanism Thermal Evaporation Valve lost after a reconnection

### ISSUE THREAD

**Issue by dhebert-pro** [SuperMartijn642/Entangled1.12#15]
**Version Info**
- Minecraft, 1.16.5
- Entangled, 1.2.12-mc1.16.5

**Description of the Bug**
When I have an entangled block bound to a Thermal Evaportation Plant and I connect Pipes to it all works fine. BUT when I disconnect my game and reconnect, each pipe no longer works.
Pipez pipes stops to give water, Mekanism Thermal Pipes are disconnected.
Classic Entangled connections and direct piping in TEP work fine though.

**Steps to Reproduce**
- Construct a Thermal Evaporation Plant
- Bind the valve to the Entangled Block
- Connect pipes to the Entangled Block (for me it is Pipez fluid pipes connected to a sink and Thermodynamic Mekanism pipes connected to a resistive heater)
- Check that all works as intended
- Close the game
- Reopen the game
- Check that no more water is inserted in the TEP and that Thermodynamic pipes are no more connected.

**Screenshots**
![2021-04-14_08 14 58](https://user-images.githubusercontent.com/40596939/114976246-f00aa300-9e85-11eb-9ca9-926c054f4288.png)
![2021-04-14_08 09 45](https://user-images.githubusercontent.com/40596939/114976250-f13bd000-9e85-11eb-9ff9-74d9d53421b2.png)

**Comment by SuperMartijn642** [comment]
Whoops forgot all about this issue, but pipes should no longer disconnect now.

Thank you for reporting the issue!
