### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by Diversion98** [SuperMartijn642/Entangled1.12#18]
**Version Info**
- Minecraft, 1.16.5
- Entangled, 1.3.0
- Forge, 36.1.18

**Steps to Reproduce**
update Entangled to version 1.3.0 and start server with a new world
version 1.2.12 works perfectly

this is only on a server, the client doesn't crash

**Crash report (~/logs/latest.log)**
[crash-2021-05-18_17.27.21-fml.txt](https://github.com/SuperMartijn642/Entangled1.12/files/6502517/crash-2021-05-18_17.27.21-fml.txt)
[2021-05-18-1.log](https://github.com/SuperMartijn642/Entangled1.12/files/6502519/2021-05-18-1.log)

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.3.1.

Thank you for reporting the issue!
