### ISSUE TITLE
[Crash] Crashing while in a server

### ISSUE THREAD

**Issue by Sunconure11** [SuperMartijn642/Entangled1.12#19]
**Version Info**
- Minecraft, 1.12.2
- Entangled, 1.3.1

**Crash report (~/logs/latest.log)**
https://paste.dimdev.org/oqigapukef.mccrash

**Comment by SuperMartijn642** [comment]
This seems to be a client crash, did the server or client crash?
When does the crash occur?

**Comment by SuperMartijn642** [comment]
Actually, I fixed it now in version 1.3.2.

Thanks for reporting the crash, although please fill out the template next time.
