### ISSUE TITLE
[Feature] Target Block Blacklist

### ISSUE THREAD

**Issue by TemperedFool** [SuperMartijn642/Entangled1.12#20]
**Is your feature request related to a problem? Please describe.**
From a pack development perspective, it would be nice if we could set up a blacklist of blocks/TE's that aren't allowed to be entangled. The example that comes to mind is with Mekanism Fission waste - the mod intends that there is no way to bypass the risk of waste spilling, and it's blacklisted from transport via Quantum Entangolooper. With Entangled it's pretty trivial to teleport the waste thousands of blocks away and just let it leak into the environment by entangling a waste barrel or pressurized tube.

**Describe the solution you'd like**
A blacklist option in the config would get the job done. Feel free to implement it more fancy than that if you like!

**Comment by Linguardium** [comment]
I feel a block tag would be a better option. Running into crashing issues with MI and would like a way to blacklist. Would help prevent issues like the AE2 issue by blacklist tagging its blocks as well.

**Comment by SuperMartijn642** [comment]
I have now added a blacklist tag for blocks that cannot be targeted by an entangled block. Whenever the block at the targeted location is in the blacklist, the entangled block will show a red border and any interaction with the entangled block, like pipes or redstone, won't work.
The tag id is `entangled:invalid_targets`.

This is available in Entangled version 1.3.17.
Thank you for the suggestion!
