### ISSUE TITLE
[Bug] New One Probe Feature Does Not Work Properly on Servers

### ISSUE THREAD

**Issue by Darkosto** [SuperMartijn642/Entangled1.12#24]
**Version Info**
- Minecraft, 1.16.5
- Forge: 36.1.33
- Entangled, 1.3.5a

**Description of the Bug**

The tooltip while looking at an Entangled block shows: "Error: Entangled". I confirmed it works properly on Single Player.

![image](https://user-images.githubusercontent.com/10309699/125841919-cc2c866b-a959-4b46-b852-46ef2388ee85.png)

**Comment by SuperMartijn642** [comment]
Whoops, I just copied my WAILA code for The One Probe. However, turns out The One Probe creates the tooltip server-side and sends it to the client, while WAILA just creates the tooltip client-side.
I fixed it now in version 1.3.6.

Thank you for reporting the issue!
