### ISSUE TITLE
[Crash] NoClassDefFoundError when no TheOneProve installed

### ISSUE THREAD

**Issue by frank89722** [SuperMartijn642/Entangled1.12#25]
**Version Info**
- Minecraft, 1.16.5
- Entangled, 1.3.5a

**Steps to Reproduce**
Run the game without TheOneProbe

**Crash report (~/logs/latest.log)**
https://gist.github.com/frank89722/186ac3e477393ef807373a45c4905190

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.3.6.

Thank you for reporting the issue!
