### ISSUE TITLE
[Crash] TOP + Entangled 1.17 crash

### ISSUE THREAD

**Issue by PokeMaserJ** [SuperMartijn642/Entangled1.12#26]
**Version Info**
- Minecraft, ... 1.17.1
- Entangled, ... 1.3.6
- TOP, ... 4.0.2

**Steps to Reproduce**
... Launch the game with these mods, TOP will fail to load,  caused by your integration seemingly 

**Crash report (~/logs/latest.log)** 
... https://gist.github.com/PokeMaserJ/0f7e91e8cc7ecafd43918dab917e554e

**Comment by SuperMartijn642** [comment]
Seems The One Probe 4.0.1 had a breaking API change. It is fixed now in Entangled 1.3.6a for 1.17.

Thank you for notifying me and reporting it!
