### ISSUE TITLE
[Crash] When Making a Loop of Entangled Blocks

### ISSUE THREAD

**Issue by Darkosto** [SuperMartijn642/Entangled1.12#29]
**Version Info**
- Minecraft, 1.16.5
- Entangled, 1.3.7

**Steps to Reproduce**
1. Place down 2 or more Entangled Blocks
2. Entangle each one to the previous block
3. Entangle the last block to the first one in the line
4. Crash

![2021-11-11_16 39 51](https://user-images.githubusercontent.com/10309699/141389007-5d35cbf4-a924-4291-95cb-e330342adfc6.png)
**Crash report (~/logs/latest.log)**

https://pastebin.com/eacWs1iY

**Comment by SuperMartijn642** [comment]
Yup, I forgot to account for infinite loops when requesting the redstone values 🤦‍♂️

I also noticed entangled blocks linked to other entangled block didn't actually work, but they were rendered. So I made it so they work up to 10 connections deep now, just like they're rendered.

I fixed these things now in Entangled version 1.3.8.

Thank you for reporting the issue!
