### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by ChromaPIE** [SuperMartijn642/Entangled1.12#3]
Using Entangled 1.2.4. Firstly thanks for this mod. It's a masterpiece, bringing automation lines more tidy.

Here is a little problem which I believe is related to the rendering: when binding Tanks from Large Fluid Tank (https://www.curseforge.com/minecraft/mc-mods/largefluidtank), to the Entangled Block, a weird block-like phantom, seemingly staying at a somehow fixed position, would appear when being around the Entangled Block. Here is a screenshot: https://imgur.com/a/Jfgqvuh

In the screenshot you can see that, I binded a Emerald Tank from LFT, which contained some Hydrogen, to the Entangled block. When I got near to it, the weird phantom would appear, but after removing the Entangled Block from the world, the phantom would vanish immediately, and this is also why I am pretty sure that it's the Entangled Block which caused the problem.

My request is: is this repairable? If not, is it possible to add a config, by which players can choose not to render the exact model of the target block, but just an icon of it displaying on each side of the Entangled Block? Maybe it'll cure the rendering problem, meanwhile maybe more friendly to PCs which can't take too much from rendering.

**Comment by SuperMartijn642** [comment]
What Minecraft version are you using?
I assume Large Fluid Tank's tanks use a tile entity renderer, in that case there is not much I can do. My best solution would be to blacklist their blocks and not render them at all inside the entangled block.
Especially if you're using Minecraft 1.14 tile entitie renderers don't necessarily render where and how you tell them to.

**Comment by ChromaPIE** [comment]
My version is 1.12.2, sorry for not describing it.

As for "Blacklist", you mean just not render them or ban those tile entities from LFT from binding to the Entangled Block? If just keep the Entangled Block from rendering them, that'll be perfect.

**Comment by SuperMartijn642** [comment]
I meant just not rendering them, yeah I wasn't very clear about that 😅
I'll be changing it probably sometime next week then.

**Comment by SuperMartijn642** [comment]
As of version 1.2.5 tile entities from Large Fluid Tanks no longer get rendered on 1.12 and 1.14.

**Comment by ChromaPIE** [comment]
Appreciate that! No more phantoms now with the lastest version, but in the entangled block I can still see the tank spining inside, which is just amazing.

**Comment by SuperMartijn642** [comment]
Yeah luckily the tank itself is just the normal model and only the fluid inside is rendered by the tile entity.
