### ISSUE TITLE
[Bug] RF doesn't transfer

### ISSUE THREAD

**Issue by TheSlicer7791** [SuperMartijn642/Entangled1.12#30]
**Version Info**
Minecraft, 1.16.5
Entangled, 1.3.6

**Description of the Bug**
power doesn't transfer though the entangled block with a compression dynamo, pipe connects but no rf goes through. tried with different cables and the dynamo is running and the cables are compatible.

**Screenshots**
![2021-11-18_17 45 36](https://user-images.githubusercontent.com/31602320/142508841-58b83bb7-eef8-44cb-a9d3-a42b5ce10f7a.png)

**Comment by SuperMartijn642** [comment]
![image](https://user-images.githubusercontent.com/12382965/142650216-ac5dbf16-0b6c-48f4-be87-48485838902c.png)
This is essential what you have. Here the compression dynamo is trying to push to its front. It doesn't find a block there and thus doesn't transfer any energy.

![image](https://user-images.githubusercontent.com/12382965/142650429-a5e59fa8-3879-4e16-9897-7d50169d9e27.png)
This is probably what you want. Here the compression dynamo finds a block in front of it. It then requests if the block can store energy. The entangled block then passes on the request to the energy cube and sends back the energy cube's response. Thus, the compression dynamo can transfer energy to the energy cube.

**Comment by SuperMartijn642** [comment]
Feel free to respond here if my solution didn't fix the problem or is unclear, and I'll reopen the issue.
