### ISSUE TITLE
[Bug] Does not send Refined Storage Links

### ISSUE THREAD

**Issue by Warzer1** [SuperMartijn642/Entangled1.12#31]
**Version Info**
- Minecraft, ...1.16.5 (modpack Ocean block 1.9)
- Entangled, ...1.3.9

**Description of the Bug**
...when entangling the Refined storage storage block into a compact machine, cables connect but don't seem to work.  Things connected to cable do not power up, or show up in the RS system
*maybe its not currently supported and if so this can be changed to a feature request.

**Steps to Reproduce**
...1. Entangle RF Block into Binder
2. move to compact machine
3. use binder on entangled block. (shows RS block)
4. connect RS fiber cable (seems to connect)
5. Connect a crafting grid
6. Result is no power to crafting grid.

Tried crafting grid directly on top of entangled block and with fiber cable.

**Screenshots**
..
![2021-11-22_13 48 49](https://user-images.githubusercontent.com/23535514/142926949-c97d32de-acb2-4e22-a961-5b1609d2e37f.png)
.

**Comment by osirisgothra** [comment]
Also in the 1.18.2 version, wasn't sure if this was intentional, but if support is ever added, hopefully we can, if not already, blacklist it on certain packs where it's existence would be undermined. (Version 1.3.11, the pack also had included the Gaz entangled fix mixin 1.0, if that matters).

**Comment by SuperMartijn642** [comment]
Copied from #27, but should hold the same for Refined Storage:
> In regards to the actual issue, the entangled blocks are not intended allow connecting Applied Energistics (AE2) networks through them. It is simply incompatible with AE2's network discovery.
The cable connected to the entangled block will tell the bound block 'hey I've been placed here on your west side, let's connect our networks'. Then when the bound block later tries to check for a block on it's west side, it won't find the cable or it might even find a different cable. This inherently leads to issues.

I have now added a blacklist feature for target blocks. By default, all Refined Storage blocks are now blacklisted to indicate you can't connect networks through the entangled block.
This is available in Entangled version 1.3.17.
Thank you for reporting the issue!
