### ISSUE TITLE
[Feature] Add toggle to "spinning" of bound block render inside of Entangled block

### ISSUE THREAD

**Issue by That-Canadian** [SuperMartijn642/Entangled1.12#33]
I personally get some headaches / nauseous feeling if I look at the Entangled blocks for too long, due to the spinning render inside of the block it is bound to.

It would be ideal if a config option was added to disable this spinning, and just have a more "static" render instead. Thanks =)

**Comment by SuperMartijn642** [comment]
Thanks for the suggestion!

I thought I already added this, but I guess I never did 🤦‍♂️whoops
I will add the option whenever I have some time available.

**Comment by SuperMartijn642** [comment]
I added the config option now in Entangled 1.3.10.

Thank you for the suggestion!
