### ISSUE TITLE
[Feature] Blacklist Render Block config options

### ISSUE THREAD

**Issue by weszhuang** [SuperMartijn642/Entangled1.12#35]
**Is your feature request related to a problem? Please describe.**
Issues with other mods rendering methods causing crashes as seen in other issues opened before.
**Describe the solution you'd like**
Add the renderblacklist to the config file.

**Comment by SuperMartijn642** [comment]
For anyone looking at this, as was discussed on Discord:
It is my intention to make the blacklists available through the config. I don't currently have an implementation for lists in my config library, so it will have to wait until I add that.

**Comment by SuperMartijn642** [comment]
A while back I added some checks so any rendering issues won't lead to crash anymore. Not sure which version I added it, but it was a while ago.

I have now also added two tags, one for blocks which should not be rendered and one for block entities which should not be rendered. The id is `entangled:render_blacklist` for both the block tag and the block entity tag.
This is available in Entangled version 1.3.17. Thank you for the suggestion!
