### ISSUE TITLE
MC 1.10.2 game crash

### ISSUE THREAD

**Issue by GIGAAj1** [SuperMartijn642/Entangled1.12#36]
I downloaded the mod from Curseforge for  MC 1.10.2 and when the game starts it says it wants MC 1.12.2 (Mod version is 1.1.1)

**Comment by SuperMartijn642** [comment]
There's no 1.10.2 version of Entangled 🤔

**Comment by GIGAAj1** [comment]
![Screenshot_20220108-081358290](https://user-images.githubusercontent.com/2996236/148635480-cfda827a-045f-4494-bce7-307a11eebad5.png)
But Curseforge said it is MC 1.10.2

**Comment by SuperMartijn642** [comment]
Then I probably checked off the wrong version, because those are definitely not made for 1.10.2.
Also, those are **really** old versions of Entangled.

I changed it now to be just 1.12 for that file.
