### ISSUE TITLE
[Crash] On startup: NoSuchFileException: ./config/entangled-common.toml

### ISSUE THREAD

**Issue by Zygahedron** [SuperMartijn642/Entangled1.12#37]
**Version Info**
- Minecraft, 1.18.1
- Forge 39.0.59
- Config lib, 1.0.9
- Core lib, 1.0.16a
- Entangled, 1.3.10
Additional info, I'm on macOS, launching through ATlauncher. My friends using the same mods can start up just fine.

**Steps to Reproduce**
Start up the game, game crashes. Not much in the way of steps.

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/Entangled/files/7965299/latest.log)
[crash-2022-01-29_23.28.33-client.txt](https://github.com/SuperMartijn642/Entangled/files/7965297/crash-2022-01-29_23.28.33-client.txt)

**Comment by SuperMartijn642** [comment]
Could you try deleting your config folder or at least the entangled config and see if it works then?

**Comment by Zygahedron** [comment]
It did this on a fresh installation with no configs. After crashing there's still no entangled config, and adding one manually doesn't affect the error at all.

**Comment by SuperMartijn642** [comment]
Does the game launch properly without Entangled?

**Comment by Zygahedron** [comment]
Yes it does. It also launches properly out of the vanilla launcher, only failing from ATLauncher.

**Comment by SuperMartijn642** [comment]
If it is specifically the ATLauncher which causes it to fail, there is likely nothing I can do about it. It probably has to with permissions to access/create the config file.
