### ISSUE TITLE
[Bug] Failed to export Entangled Block FE

### ISSUE THREAD

**Issue by XieDeWu** [SuperMartijn642/Entangled1.12#40]
**Version Info**
- Minecraft 1.18.2
- Entangled 1.3.11

**Description of the Bug**

Failed to export Entangled Block FE
But Importing Entangled Block FE Succeeded

**Steps to Reproduce**
...

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
I have no clue what you mean. Could you give a description of what you are trying to do or share some screenshots?

**Comment by XieDeWu** [comment]
https://user-images.githubusercontent.com/49677093/171787704-575e65c7-34b9-41e8-b4a0-d95d37b9516b.mp4

Example:
Proxy Mekanism FE container ,Entangle Block FE extraction failed,The same is true for other containers that support FE extraction

**Comment by XieDeWu** [comment]
https://user-images.githubusercontent.com/49677093/171788789-60ab48de-19de-4676-a356-26b5d6f09769.mp4

Example:
Proxy Mekanism FE container ,Entangle Block FE extraction failed,The same is true for other containers that support FE extraction

**Comment by XieDeWu** [comment]
https://user-images.githubusercontent.com/49677093/171789223-32859ace-3527-451e-9d96-8b92f8512df4.mp4

Example:
Proxy Mekanism FE container 
,Entangle Block FE extraction failed
,The same is true for other containers that support FE extraction
,For items and fluids, the agent's passive IO is fine

**Comment by XieDeWu** [comment]
https://user-images.githubusercontent.com/49677093/171789452-4af1dc48-d5d0-4af8-bfb5-741b9adb4fbe.mp4

Example:
Proxy Mekanism FE container
,Entangle Block FE extraction failed
,The same is true for other containers that support FE extraction
,For items and liquids, agent passive IO works fine

**Comment by XieDeWu** [comment]
> I have no clue what you mean. Could you give a description of what you are trying to do or share some screenshots?


https://user-images.githubusercontent.com/49677093/171821078-29b5977a-94bf-43ba-9864-d959d5d3255b.mp4

Example:
Proxy Mekanism FE container
,Entangle Block FE extraction failed
,The same is true for other containers that support FE extraction
,For items and liquids, agent passive IO works fine
