### ISSUE TITLE
[Bug] Redstone only works one way

### ISSUE THREAD

**Issue by HumanGamer** [SuperMartijn642/Entangled1.12#42]
**Version Info**
- Minecraft, 1.18.2
- Entangled, 1.3.11

**Description of the Bug**
If you entangle a redstone block, lever, button, etc, it will produce output on the entangled block, however, entangling redstone dust does not work, and entangling a piston and trying to power the entangled block does not work.

**Steps to Reproduce**
Entangle any block that can receive power and then attempt to power the entangled block, the source block won't be powered.

**Screenshots**
![2022-07-22_16 22 45](https://user-images.githubusercontent.com/39096122/180570468-e573ea4c-eab4-402c-a2ff-1af02f95389d.png)

**Comment by SuperMartijn642** [comment]
This is simply a limitation of Minecraft. That piston needs some block around it to emit a redstone signal. The other way around, I can just make the entangled block emit the redstone.
