### ISSUE TITLE
[Bug] [1.16.5] Latest version closes the game before loading can begin

### ISSUE THREAD

**Issue by 2ndkirbyever** [SuperMartijn642/Entangled1.12#48]
**Version Info**
- Minecraft, 1.16.5
- Entangled, 1.3.12

**Description of the Bug**
After updating to Entangled 1.3.12, Forge does not get to finish scanning the mods. The game closes outright and the launcher reports an exit code of 1.

**Steps to Reproduce**

1. Create a new 1.16.5 profile on Curseforge.
2. Install Entangled.
3. Attempt to launch the game.
4. The game crashes before it can even lift off.

**Comment by SuperMartijn642** [comment]
I cannot reproduce the issue, Minecraft starts up fine with Entangled 1.3.12 and my core library 1.1.0 and config library 1.1.6.
Could you upload the `~/logs/latest.log` file?

**Comment by 2ndkirbyever** [comment]
Well, now I can't reproduce it either. I'm honestly not sure what changed between me opening this issue and now.
