### ISSUE TITLE
Crash when looping Entangled Blocks

### ISSUE THREAD

**Issue by jamesjimmy88** [SuperMartijn642/Entangled1.12#5]
If you link two or more Entangled Blocks to each other the game will crash.
Console log:
https://gist.github.com/jamesjimmy88/674c57e1268578cbc0c69957c97f90fb

Tested with Entangled 1.2.5 on forge 32.0.108 (minecraft 1.16.1)

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.2.7.

Thanks for the report!
