### ISSUE TITLE
Fluid Pipes disconnect after restrat

### ISSUE THREAD

**Issue by Vo1d88** [SuperMartijn642/Entangled1.12#55]
**Version Info**
- Minecraft, 1.19.2
- Entangled, entangled-1.3.13-forge-mc1.19

**Description of the Bug**
The pipes from the Pipez mod disconnect after world restart. It started happening after I updated entangled from 1.3.12 to 1.3.13. FYI, the entangled block is connected to a drawer controller on another dimension, chunk loaded

**Steps to Reproduce**
go to a dimension, place a drawer controller, change dimension, place and connect the entangled block to the drawer controller, place a pipe from the Pipez mod to extract items/fluids. After world restart the pipe disconnects.

![2023-02-26_16 31 27](https://user-images.githubusercontent.com/123479379/221420629-39e2e704-12e3-4e58-aab2-43add98dc40f.png)
![2023-02-26_16 54 29](https://user-images.githubusercontent.com/123479379/221421330-caba67a3-7ef0-41a6-8c61-20fd5a866797.png)
![2023-02-26_16 52 20](https://user-images.githubusercontent.com/123479379/221421339-c17f0daa-3915-40bc-b199-46f1e01d7470.png)
![2023-02-26_16 53 39](https://user-images.githubusercontent.com/123479379/221421343-1a7db689-a6e4-481e-a402-554a81b15b39.png)

**Comment by Vo1d88** [comment]
I've tested it with a tank and chest in the same dimension, it's the same, it disconnects.
![2023-02-26_16 59 27](https://user-images.githubusercontent.com/123479379/221421731-b3b866a1-ab47-407f-9b9d-6de6a409b0ce.png)
![2023-02-26_17 00 58](https://user-images.githubusercontent.com/123479379/221421736-772d7edf-e5c7-47bb-9853-b68c2f017ed7.png)

**Comment by Vo1d88** [comment]
I reverted it back to 1.3.12, and now it works just fine

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.3.14.
Thank you for reporting the issue!
