### ISSUE TITLE
[Crash] ...java.lang.NullPointerException: Exception ticking world

### ISSUE THREAD

**Issue by slebreton79** [SuperMartijn642/Entangled1.12#59]
**Version Info**
- Minecraft, 1.12.2
- Entangled, 1.3.13

**Steps to Reproduce**
...Only Minecraft  1.12.2 and forge ver: 2860 only mod installed is entangle 1.3.13,  supermartijn642configlib-1.1.6, supermartijn642corelib-1.1.9a, bind any minecraft block to entangled block and crashes

**Crash report (~/logs/latest.log)**
...
[latest.log](https://github.com/SuperMartijn642/Entangled/files/11585037/latest.log)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.3.13a for Forge on 1.12.
Thank you for reporting the issue!
