### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by ArturilloD** [SuperMartijn642/Entangled1.12#6]
The improvements that I think are interesting are that it would be good if when linking a block it could be good to link the block itself, not the position of the block, that is, for example using dank storage I link it and there I can make items enter in that inventory, but when they take it they no longer continue to enter, if instead they linked with that block they could take it and they would continue entering.

The second improvement would be interesting for example with pipes such as pretty pipes or others such as mekanism, etc. Being able to put some kind of mask so that it is completely camouflaged

**Comment by SuperMartijn642** [comment]
I have no clue what you mean in your first paragraph.

I didn't really consider how cables looked when connected with an entangled block, I might change something there in the future.

**Comment by ArturilloD** [comment]
Well I'll send you a screenshot, in principle what happened to me was that
the drawers looked strange, that is, they occupy the entire block, while
the others remain spinning inside the entangled.

Regarding the cables forget it, since I think it would be a completely
different idea, that would give to create a single mod. Thanks and regards

**Comment by SuperMartijn642** [comment]
I don't see any issues with Storage Drawers, if you ever send a screenshot of the problem or a way to replicate it I will reopen the issue.
