### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by AntoFarmer0** [SuperMartijn642/Entangled1.12#60]
**Version Info**
- Minecraft, 14.23.5.2847-1.12.2
- Entangled, 1.3.14

**Steps to Reproduce**

I installed entangled in my modpack using the curseforge app and I pressed play everything worked as it should, but once the launcher started it doesn’t appear on the screen and by task management it doesn’t record any activity, I tried to remove the mod and it starts normally.

**Crash report (~/logs/latest.log)**

This is the only log i've found.

[latest.log](https://github.com/SuperMartijn642/Entangled/files/11618738/latest.log)

**Comment by SuperMartijn642** [comment]
Probably caused by RealBench. It hasn't been updated in 5 years and it source code is no longer available, so nothing I can do about it. I suggest not using RealBench.

**Comment by AntoFarmer0** [comment]
Yes RealBench was the problem thanks for your help
