### ISSUE TITLE
[Crash] Rubidium incompatibility?

### ISSUE THREAD

**Issue by mwxkhmy** [SuperMartijn642/Entangled1.12#62]
**Version Info**
- Minecraft, Forge 1.19.2
- Entangled, 1.3.14

**Steps to Reproduce**
Entangled causes a crash when installing a block in the world if Rubidium are used, Out Of Sign and Oculus mod. Rubidium this is fork Sodium on Forge. Perhaps the problem is in the rendering texture (?)
// The Tesseract mod is also the cause of the crash(

**Crash report (~/logs/latest.log)**

---

**Comment by SuperMartijn642** [comment]
Please share the logs

**Comment by mwxkhmy** [comment]
[latest.log](https://github.com/SuperMartijn642/Entangled/files/11808607/latest.log)

**Comment by SuperMartijn642** [comment]
Seems to be caused by Out Of Sight. Out Of Sight appears completely abandoned on 1.12. In fact there isn't even a 1.12 version listed on their mod page.
I would suggest not using Out Of Sight.

**Comment by mwxkhmy** [comment]
And indeed, Out Of Sight conflicts. It's a pity that they can't be used together...
Thanks!!
