### ISSUE TITLE
[Crash] ...Server Crash

### ISSUE THREAD

**Issue by instinxx** [SuperMartijn642/Entangled1.12#68]
**Version Info**
- Minecraft, 1.20.1
- Entangled, 1.3.15 for Forge

**Steps to Reproduce**
Player reported that once he placed the block, server crashed, At this point it crashes if anyone get near the location

**Crash report (~/logs/latest.log)**
...
https://pastebin.com/FkgzAzJm  - Crash Log
https://pastebin.com/xsCVhWwi  - Latest.log

**Comment by SuperMartijn642** [comment]
This has been fixed by Powah, so I'll close the issue.
