### ISSUE TITLE
[Bug] Big cordinates cause highlight location to be not precise

### ISSUE THREAD

**Issue by YiRanMushroom** [SuperMartijn642/Entangled1.12#69]
**Version Info**
- Minecraft, 1.12.2
- Entangled, 1.3.16

**Description of the Bug**
When cordinates  are big, the highlight  location would have big mistake

**Steps to Reproduce**
I use 30000,80,10000, which a huge offset can be witnessed

**Screenshots**

![2023-10-11_16 47 12](https://github.com/SuperMartijn642/Entangled/assets/114495322/5a61a15c-618d-4737-a7c5-56648900bf67)

--------------------------------------------
Probably because of the float calculation's uncertainty

**Comment by YiRanMushroom** [comment]
May be just use Integer rather than Double, Because I don't know why you need to use float to render.

**Comment by SuperMartijn642** [comment]
> May be just use Integer rather than Double, Because I don't know why you need to use float to render.

Wut

I have fixed the issue now in version 1.3.16a.
Thank you for reporting the issue!
