### ISSUE TITLE
Mistakes

### ISSUE THREAD

**Issue by ArturilloD** [SuperMartijn642/Entangled1.12#7]
The textures do not look good with the storage drawers (https://www.curseforge.com/minecraft/mc-mods/storage-drawers) and also the game crashes when linked with any type of XNet connector (https: / /www.curseforge.com/minecraft/mc-mods/xnet), with cables does not happen.

[crash-2020-09-03_16.51.26-client.txt](https://github.com/SuperMartijn642/Entangled1.12/files/5169404/crash-2020-09-03_16.51.26-client.txt)
[debug.log](https://github.com/SuperMartijn642/Entangled1.12/files/5169406/debug.log)
[latest.log](https://github.com/SuperMartijn642/Entangled1.12/files/5169408/latest.log)

**Comment by SuperMartijn642** [comment]
I can't find anything wrong when interacting with Storage Drawers, could you maybe share a screenshot of what you mean?

The crash is caused by XNet. I have created [a pull request to fix it](https://github.com/McJtyMods/XNet/pull/434).

**Comment by SuperMartijn642** [comment]
Up to XNet to fix this issue now.
