### ISSUE TITLE
[Bug] RS and AE blacklists can be bypassed.

### ISSUE THREAD

**Issue by Kevin-Marsh** [SuperMartijn642/Entangled1.12#70]
- Minecraft: 1.20.1
- Entangled: 1.3.17

The new blacklist setup for Applied Energistics and Refined Storage are very easy to bypass. The mods extendedae and Mega Cells add interfaces for AE that can still be bound and the mod Cable Tiers adds interfaces for RS that also still work. I thought it worth mentioning if you wanted to expand your blacklist and prevent it from working with RS or AE fully.

**Comment by SuperMartijn642** [comment]
I have removed the blacklists for AE2 and RS now, so this should no longer be relevant.
