### ISSUE TITLE
[Bug] Bound entangled blocks can no longer be placed without resetting them

### ISSUE THREAD

**Issue by MuteTiefling** [SuperMartijn642/Entangled1.12#71]
**Version Info**
- Minecraft, 1.19.2
- Entangled, 1.3.17

**Description of the Bug**
Since the blacklist was implemented (https://github.com/SuperMartijn642/Entangled/issues/27) bound entangled blocks may no longer be placed. Attempting to place one results in the following message. 

`Binder is bound to unknown dimension 'minecraft:'`

The block may only be placed again if it is cleared by re-crafting it. 

**Steps to Reproduce**
1. Place an entangled block
2. Bind to some block
3. Break the entangled block
4. Attempt to place it again

**Screenshots**
Video: https://streamable.com/5m9e33

As a side note, I think the blacklist is a great tool, but the default of blocking all of ae2/rs across the board feels like too broad a stroke. Entangled blocks have worked fine for years to insert into Interfaces and provide power to Controllers; all the things a reasonable player would expect them to work with. I have worlds where P2P inputs are entangled, allowing me to input into them further away. Pattern interfaces are entangled, allowing me to send the result of a craft back to it to trigger the next. I feel this default blacklist breaks more of the good functionality than it truly fixes. 

Rather, it seems to me that a simple copypasta explaining why they cannot work with networking would serve you better and help people understand how these are meant to work. Not everyone understands what the capability system does, and trust me we've fielded a lot of questions in our discord from players who don't understand how they work. A brief explanation has been enough to set them straight though. Will you get questions about it still? Absolutely. But you can just point people at the copypasta and leave it at that. 

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/883

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.3.18.
Thank you for reporting the issue!

**Comment by SuperMartijn642** [comment]
Blacklists for Applied Energistics and Refined Storage have also been removed.
