### ISSUE TITLE
[Crash] when starting modpack after installing entangled

### ISSUE THREAD

**Issue by CookieKiller01** [SuperMartijn642/Entangled1.12#72]
**Version Info**
- Minecraft, 1.19.2
- Entangled, 1.3.17

**Steps to Reproduce**
Start Techopolis2 after installing entangled
**Crash report
[crash-2024-03-02_19.02.37-client.txt](https://github.com/SuperMartijn642/Entangled/files/14470352/crash-2024-03-02_19.02.37-client.txt)
 
i couldnt find any incompatibilities for entangled that would cause the crash, and i have no idea why it crashes.

**Comment by SuperMartijn642** [comment]
Did you install the dependencies for Entangled? Normally you get a warning screen, however Oculus causes a crash when that screen is shown.

**Comment by CookieKiller01** [comment]
oh, didnt saw that it has dependencies, now it functions just fine. thanks
