### ISSUE TITLE
[Crash]Moving the mouse over any block bound to certain dimensions using the Entangled Binder causes the game to crash.

### ISSUE THREAD

**Issue by xiaojing911** [SuperMartijn642/Entangled1.12#76]
**Version Info**
- Minecraft,1.12.2
- Entangled,1.3.17

**Steps to Reproduce**
1.Enter the dimensions you have created or any dimensions within the Utility Worlds mod.
2. Use the Entangled Binder to bind any block within the dimension.
3. Upon opening the inventory and hovering the mouse over the Entangled Binder that has been bound within the dimension, the game crashes.

**Screenshots**:
Video:Utility Worlds:https://streamable.com/qdlrlq
                    Custom Dimensions:https://streamable.com/qdlrlq

Crash report 
[crash-2024-04-05_21.35.14-client.txt](https://github.com/SuperMartijn642/Entangled/files/14885637/crash-2024-04-05_21.35.14-client.txt)
[crash-2024-04-05_21.37.12-client.txt](https://github.com/SuperMartijn642/Entangled/files/14885640/crash-2024-04-05_21.37.12-client.txt)

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.3.18.
Thank you for reporting the issue!
