### ISSUE TITLE
[Bug] The Entangled Binder cannot unbind blocks after they have been bound.

### ISSUE THREAD

**Issue by xiaojing911** [SuperMartijn642/Entangled1.12#77]
**Version Info**
- Minecraft, 1.12.2
- Entangled, 1.3.17

**Description of the Bug**
The Entangled Binder cannot unbind blocks after they have been bound.

**Steps to Reproduce**
1.The Entangled Binder is bound to any block.
2. After unbinding, the information of the Entangled Binder bound block is still visible in the inventory.

**Screenshots**
Video: https://streamable.com/j2b6fo

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.3.18.
Thank you for reporting the issue!
