### ISSUE TITLE
[Crash] Game crashes when opening any inventory besides the players with the entangled binder bound to any block.

### ISSUE THREAD

**Issue by CalebMcElderry** [SuperMartijn642/Entangled1.12#82]
**Version Info**
- Minecraft, 1.12.2
- Entangled, 1.3.18a-forge-mc1.12

**Steps to Reproduce**
Bind the entangled binder to any block then open any inventory besides the players, ex: chest, backpack, trashcan from FTB Utils.

[latest.log](https://github.com/SuperMartijn642/Entangled/files/15439588/latest.log)
[crash-2024-05-24_15.14.37-client.txt](https://github.com/SuperMartijn642/Entangled/files/15439589/crash-2024-05-24_15.14.37-client.txt)

**Comment by slebreton79** [comment]
Issue still happens with 1.3.18a
[crash-2024-08-22_15.20.30-client.txt](https://github.com/user-attachments/files/16719156/crash-2024-08-22_15.20.30-client.txt)

**Comment by SuperMartijn642** [comment]
This has been fixed now in Entangled version 1.3.19.
Thank you for reporting the issue!
