### ISSUE TITLE
[Crash] Loop bound crash

### ISSUE THREAD

**Issue by issue14** [SuperMartijn642/Entangled1.12#85]
**Version Info**
- Minecraft, 1.20.4, NeoForge 20.4.237
- Entangled, 1.3.18

**Steps to Reproduce**
Bound Entangled#1 to Entangled#2
Bound Entangled#2 to Entagled#1
Trying to break

![crash]()

**Crash report (~/logs/latest.log)**
[latest.txt]() (Can't upload with a .log)

**Notes**
I was unable to reproduce this bug on the Fabric (0.15.11)

**Comment by SuperMartijn642** [comment]
This has been fixed now in Entangled version 1.3.19 for NeoForge 1.20.4 - 1.21.1.
Thank you for reporting the issue!
