### ISSUE TITLE
[Feature] Russian translation

### ISSUE THREAD

**Issue by Dorfyt** [SuperMartijn642/Entangled1.12#88]
I'd like to add russian translation, but creating fork and pr for every version manually is pain.
Pls merge ru_ru from https://github.com/EnderDrag0n/Entangled/blob/forge-1.15/src/main/resources/assets/entangled/lang/ru_ru.json into other versions

**Comment by SuperMartijn642** [comment]
Can you create a pull request for it? Which branch does not matter, but I have no way to pull your commit.

**Comment by Dorfyt** [comment]
> Can you create a pull request for it? Which branch does not matter, but I have no way to pull your commit.

https://github.com/SuperMartijn642/Entangled/pull/92#issue-2483089833

**Comment by SuperMartijn642** [comment]
Thanks! The translations are available in Entangled version 1.3.19.
