### ISSUE TITLE
[Crash] Soft Crash when joining LAN world

### ISSUE THREAD

**Issue by NielsPilgaard** [SuperMartijn642/Entangled1.12#89]
**Version Info**
- Minecraft, 1.21
- Entangled, 1.3.18

**Steps to Reproduce**
- Start a LAN world
- Join the LAN world with another user
- Soft crash / joining fails

**Crash report (~/logs/latest.log)**
https://gist.github.com/NielsPilgaard/8ceb945422527288d2da7f3ee31b38e8

**Comment by SuperMartijn642** [comment]
Fixed now in Entangled version 1.3.18a for Minecraft 1.20.6-1.21.
Thank you for reporting the issue!
