### ISSUE TITLE
[Feature] Add a config file with parameters like disabling cross-dimensional use and setting a max range

### ISSUE THREAD

**Issue by ghost** [SuperMartijn642/Entangled1.12#9]
**Is your feature request related to a problem? Please describe.**
In their current state, the entanglement blocks are almost too powerful, and I'd like the option to disable these features to make them more "fair".

**Describe the solution you'd like**
A config file that offers a maximum range(setting it to -1 could enable infinite range), and a toggle for enabling/disabling cross dimensional use.

**Comment by SuperMartijn642** [comment]
I added both settings in a config now in version 1.2.9.

Thanks for the great suggestion!
