### ISSUE TITLE
[Feature] Round-Robin Support

### ISSUE THREAD

**Issue by SeyfertGames** [SuperMartijn642/Entangled1.12#96]
**Is your feature request related to a problem? Please describe.**
Yes. 1 Sodium-Cooled Fission Reactor with 2 Boilers. I want to distribute Heated Sodium between the two boilers evenly through Point-to-Point reactor ports, but it doesn't Round-Robin.

**Describe the solution you'd like**
Support for Round-Robin. That way, it is evenly distributed if you have two entangled blocks connected to the same block.

**Comment by SuperMartijn642** [comment]
I am unsure as to what you mean. The entangled blocks don't really distribute anything. Connecting pipes to them is as if connecting pipes to the block they are bound to.

**Comment by SeyfertGames** [comment]
> I am unsure as to what you mean. The entangled blocks don't really distribute anything. Connecting pipes to them is as if connecting pipes to the block they are bound to.

Yeah, I can see since it just carries over the function of the block it's bound to... But I wonder why it doesn't have the same evenly distributed output to both boilers. Could it be Mekanism itself?

**Comment by SuperMartijn642** [comment]
I don't really understand your setup or what you're trying to do. I haven't used Fission reactors or boilers from Mekanism.

**Comment by SeyfertGames** [comment]
> I don't really understand your setup or what you're trying to do. I haven't used Fission reactors or boilers from Mekanism.

This is how I have it arranged.
![image](https://github.com/user-attachments/assets/227482ff-d27e-40bf-a1a5-8f53f3af149e)
This is the boiler that is not getting the Heated Sodium.
![image](https://github.com/user-attachments/assets/a3d21347-6ea8-436c-9c0f-3f63d90c9714)
And is the Boiler that is getting all of the Heated Sodium.

They are both bound to the same port on the reactor, but only one boiler is getting the Heated Sodium.

**Comment by SeyfertGames** [comment]
What I'm wondering is, why is it that even though there connected to the same port, only one is getting the Heated Sodium.

**Comment by SuperMartijn642** [comment]
If I understand correctly, the structure in the back is the boiler? Is the boiler pulling stuff from the entangled blocks? In that case, the entangled blocks aren't really doing anything, it is simply which boiler happens to tick first and thus extract first.
You'd have the same behaviour if you had the boilers extract from the bound block directly

**Comment by SeyfertGames** [comment]
> If I understand correctly, the structure in the back is the boiler? Is the boiler pulling stuff from the entangled blocks? In that case, the entangled blocks aren't really doing anything, it is simply which boiler happens to tick first and thus extract first. You'd have the same behaviour if you had the boilers extract from the bound block directly

Ah, so its a Mekanism problem. If the Reactor Ports were Round-Robin, this wouldn't happen. I'll make an issue in Mekanism and reference this.

**Comment by SuperMartijn642** [comment]
Wut, if I understand it correctly, you have two blocks, the two boiler ports, extracting from one block which holds liquids. What exactly do you wan to round robin? You cannot make two unrelated port blocks somehow coordinate which one is going to extract from the block.

**Comment by SeyfertGames** [comment]
> Wut, if I understand it correctly, you have two blocks, the two boiler ports, extracting from one block which holds liquids. What exactly do you wan to round robin? You cannot make two unrelated port blocks somehow coordinate which one is going to extract from the block.

If the Reactor Port was Round-Robin it would evenly distribute between the two Boilers.

**Comment by SuperMartijn642** [comment]
The reactor port is the block the boiler ports are extracting from right? That block itself is then not really doing anything and it can't know how many things are gonna try to extract from it
